# Generated by Django 5.2.14 on 2026-06-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_rename_commnet_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commnets',
            new_name='comments',
        ),
    ]
